name: CI

on:
  push:
    branches: ["master", "work"]
  pull_request:
    branches: ["master"]

jobs:
  # Comprehensive test suite
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Create production bundle
        run: npm run bundle
        
      - name: Run all unit tests
        run: npm run test:unit
        
      - name: Run migration tests  
        run: npm run test:migration
        
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
        
      - name: Run E2E tests
        run: npm run test:e2e:ci
        env:
          CI: true
          
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
          
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30

  # Unit tests and build validation (keeping for backwards compatibility)
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Run all unit tests
        run: npm run test:unit
        
      - name: Run migration tests  
        run: npm run test:migration
        
      - name: Run bundle creation test
        run: npm run bundle

  # E2E tests with Playwright (keeping for backwards compatibility)
  e2e-tests:
    runs-on: ubuntu-latest
    needs: test-suite
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
        
      - name: Build project
        run: npm run build
        
      - name: Run E2E tests (Playwright)
        run: npm run test:e2e:ci
        env:
          CI: true
          
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
          
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
